# Generated by Django 5.0.6 on 2024-07-08 16:10

import registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_code', models.CharField(default=registration.models.code_generator, max_length=12)),
            ],
        ),
    ]
