stages:
  - pull
  - build

before_script:
  - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"

pull:
  stage: pull
  script:
    - docker pull "$CI_REGISTRY_IMAGE":latest
  allow_failure: true

build:
  stage: build
  script:
    - docker build --tag="$CI_PIPELINE_ID":"$CI_COMMIT_REF_NAME" --cache-from="$CI_REGISTRY_IMAGE":latest .


