# Generated by Django 5.0.6 on 2024-07-09 15:27

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banner_picture',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.get_banner_picture_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.get_profile_picture_upload_path),
        ),
    ]
